// Products
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const PRODUCT_RESET = 'PRODUCT_RESET';
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';

// files
export const UPLOAD_FILE_RESET = 'UPLOAD_FILE_RESET';
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';

export const UPDATE_FILE_RESET = 'UPDATE_FILE_RESET';
export const UPDATE_FILE_REQUEST = 'UPDATE_FILE_REQUEST';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_FAILED = 'UPDATE_FILE_FAILED';

export const DELETE_FILE_RESET = 'DELETE_FILE_RESET';
export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILED = 'DELETE_FILE_FAILED';


// leaders

export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_LOADING = 'LEADERS_LOADING';
export const LEADERS_FAILED = 'LEADERS_FAILED';

export const LEADER_RESET = 'LEADER_RESET';
export const LEADER_REQUEST = 'LEADER_REQUEST';
export const LEADER_SUCCESS = 'LEADER_SUCCESS';
export const LEADER_FAILED = 'LEADER_FAILED';

// Feedback
export const FEEDBACK_REQUEST = 'FEEDBACK_REQUEST';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_FAILED = 'FEEDBACK_FAILED';

// Registration
export const REGISTER_RESET = 'REGISTER_RESET';
export const REGISTER_REQUEST = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// Authentication
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_RESET= 'LOGOUT_RESET';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const AUTHENTICATED_QUERY = 'AUTHENTICATED_QUERY';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const IS_NOT_AUTHENTICATED = 'IS_NOT_AUTHENTICATED';

// Restore Password
export const RESTORE_RESET = 'RESTORE_RESET';
export const RESTORE_REQUEST = 'RESTORE_REQUEST';
export const RESTORE_SUCCESS = 'RESTORE_SUCCESS';
export const RESTORE_FAILED = 'RESTORE_FAILED';

export const CHANGEPASSWORD_RESET = 'CHANGEPASSWORD_RESET';
export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAILED = 'CHANGEPASSWORD_FAILED';

// Maps API keys
export const MAPS_LOADING = 'MAPS_LOADING';
export const MAPS_FAILED = 'MAPS_FAILED';
export const ADD_MAPS = 'ADD_MAPS';